name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run generate

      - name: Add .nojekyll file
        run: touch .output/public/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          repository-name: manuelwaltschek/manuelwaltschek.github.io
          branch: main
          folder: .output/public
          clean: true
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: 'Deploy modern Vue.js website with primary color #2962B3'
